### ISSUE TITLE
实名认证后，国内节点穿透不成功，国外节点能穿透成功

### ISSUE THREAD

**Issue by thgpddl** [natfrp/wiki#15]
实名认证后，我使用国内节点穿透本地8000端口，但是重复报错下方加粗代码，外网也无法访问
我是用国外节点穿透相同端口，却能够穿透成功
无服务
</s有89中午11:22
Aid Learning
Return To Desktop
或使用IP地址连接(不推荐):[117.174.59.99:40395]
2021/02/07 03:21:45[1][control.go:192][f7a**dhz-94423cfa[f7a大大dhz.8XHUTMLN]隧道启动成功
2021/02/07 03:22:05[I][control.go:90][f7a**dhz-94423cfa]Recover start
**2021/02/07 03:22:05[E][control.go:169][f7a**dhz-94423cfa]work connection closed before response StartWorkConn message: EOF
2021/02/07 03:22:15[E][control.go:104][f7a**dhz-94423cfa]不断线重连失败:recover to server timed out**
2021/02/07 03:22:25 [l][visitor_manager.go:62][f7a**dhz-94423cfa] gracefully shutdown visitor manager
2021/02/07 03:22:25[1][service.go:193][f7a**dhz-94423cfa]正在尝试重连节点..-
2021/02/07 03:22:25[l][control.go:422][f7a**dhz-94423cfa]worker shutdown
2021/02/07 03:22:25[1][service.go:357][f7a**dhz-94423cfa]连接节点成功,获得run ID [f7a**dhz-94423cfad8a61d65]，节点UDP端口[7001]
2021/02/07 03:22:25[l][service.go:195][f7a**dhz-94423cfa] login done
2021/02/07 03:22:25[1][proxy_manager.go:146][f7a**dhz-94423cfa]隧道连接中:[f7a**dhz.8XHUTMLN]
2021/02/07 03:22:25[1][control.go:362][f7a**dhz-94423cfa]Speed Limit has been updated: 1310720 bytes/s
TCP类型隧道启动成功
使用[cn-dy-yd.sakurafrp.com:40395]来连接到你的隧道或使用IP地址连接(不推荐): [117.174.59.99:40395]
2021/02/07 03:22:25[1][control.go:192][f7a**dhz-94423cfa[f7a**dhz.8XHUTMLN]隧道启动成功
2021/02/07 03:22:45[1][control.go:90][f7a**dhz-94423cfa]Recover start
2021/02/07 03:22:45 [E][control.go:169][f7a**dhz-94423cfa]work connection closed before response StartWorkConn message: EOF
ES  CT - ~$%&:- 1 '.，个AL: .s<l '[]("!#)l↓个

**Comment by fengberd** [comment]
如果你穿的是 HTTP，首页公告了解一下
有问题到 OWQ，issue 仅针对此文档中的问题
