### ISSUE TITLE
制作systemd服务，启动时报错

### ISSUE THREAD

**Issue by haohaogogo** [natfrp/wiki#24]
系统centos7
● frpc.service - SakuraFrp Service
   Loaded: loaded (/usr/lib/systemd/system/frpc.service; disabled; vendor preset: disabled)
   Active: activating (auto-restart) (Result: exit-code) since Tue 2021-05-18 01:28:10 UTC; 1s ago
  Process: 14604 **ExecStart=/root/frp/frpc -f o7bmrae6z0tpih8v:1308223** (code=exited, status=203/EXEC)
 Main PID: 14604 (code=exited, status=203/EXEC)

May 18 01:28:10 pachong-3.novalocal systemd[1]: Unit frpc.service entered failed state.
May 18 01:28:10 pachong-3.novalocal systemd[1]: frpc.service failed.

手动执行/root/frp/frpc -f o7bmrae6z0tpih8v:1308223 是可以启动的

**Comment by fengberd** [comment]
请在安装时按照文档中列出的步骤操作
