### ISSUE TITLE
无法登录节点，再映射TCP端口的时候报错

### ISSUE THREAD

**Issue by yinlinghunjiang** [natfrp/wiki#25]
`2021/06/27 18:45:04 W Tunnel/server 登录节点失败, 请检查网络连接: dial tcp 218.89.171.135:7000: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
Tunnel/server dial tcp 218.89.171.135:7000: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.`

**Comment by qiaoshouzi** [comment]
issue 仅针对此文档中的问题
