### ISSUE TITLE
[E] [yer**862-14a6d306] work connection closed before response StartWorkConn message: EOF

### ISSUE THREAD

**Issue by LittleLito** [natfrp/wiki#26]
时不时地报错，自己能够恢复，但作为服主还是希望得到解决方案，毕竟对玩家的游戏体验影响还是挺大的
`
TCP 类型隧道启动成功
[I] [yer**862-14a6d306] [yer**862.456] 隧道启动成功
2021/07/24 14:40:19 [I] [yer**862-14a6d306] 正在尝试重连节点...
2021/07/24 14:40:19 [I] [yer**862-14a6d306] worker shutdown
2021/07/24 14:40:19 [E] [yer**862-14a6d306] work connection closed before response StartWorkConn message: EOF
2021/07/24 14:40:19 [E] [yer**862-14a6d306] work connection closed before response StartWorkConn message: EOF
2021/07/24 14:40:19 [E] [yer**862-14a6d306] work connection closed before response StartWorkConn message: EOF
2021/07/24 14:40:19 [E] [yer**862-14a6d306] work connection closed before response StartWorkConn message: EOF
2021/07/24 14:40:19 [E] [yer**862-14a6d306] work connection closed before response StartWorkConn message: EOF
2021/07/24 14:40:19 [I] [yer**862-14a6d306] gracefully shutdown visitor manager
2021/07/24 14:40:20 [I] [yer**862-14a6d306] 连接节点成功, 获得 run ID [yer**862-14a6d306], 节点 UDP 端口 [7001]
2021/07/24 14:40:20 [I] [yer**862-14a6d306] login done
2021/07/24 14:40:20 [I] [yer**862-14a6d306] 隧道连接中: [yer**862.456]
2021/07/24 14:40:20 [W] [yer**862-14a6d306] [yer**862.456] 隧道启动错误： port already used
2021/07/24 14:40:20 [I] [yer**862-14a6d306] 限速已更新: 10 Mibit/s
TCP 类型隧道启动成功
`
如此循环往复

**Comment by renbaoshuo** [comment]
此处不是问题解答区。
