### ISSUE TITLE
[Q] 无法进行实名认证：支付宝客户端提示不支持此设备

### ISSUE THREAD

**Issue by lavacup2233** [natfrp/wiki#28]
请保留头部，如果您看不懂下面的问题，请不要点选

- [ *] [R] Check this switch if you know what you are doing.
- [ *] [U] Check this switch if your question is nonsensical.
- [ ] [R] 此问题与 [帮助文档](https://doc.natfrp.com/) 相关。
- [* ] [R] 我已浏览并搜索 [此 repo 的 issue 列表](https://github.com/natfrp/wiki/issues) 并确定没有重复问题。

[Q] 无法进行实名认证：支付宝客户端提示不支持此设备

**Comment by fengberd** [comment]
https://doc.natfrp.com/#/faq/realname

**Comment by lavacup2233** [comment]
Thanks for your comment.
