### ISSUE TITLE
[Q] 在 aidlux 上输出版本号时报 Segmentation fault 的错误

### ISSUE THREAD

**Issue by 772778995** [natfrp/wiki#41]
请保留头部，如果您看不懂下面的问题，请不要点选

- [] [R] Check this switch if you know what you are doing.
- [] [U] Check this switch if your question is nonsensical.
- [] [R] 此问题与 [帮助文档](https://doc.natfrp.com/) 相关。
- [] [R] 我已浏览并搜索 [此 repo 的 issue 列表](https://github.com/natfrp/wiki/issues) 并确定没有重复问题。

在 aidlux 上下载 Linux arm64架构的版本时，输出版本号报 Segmentation fault 的错误
![image](https://user-images.githubusercontent.com/65562549/153771534-850e62aa-9b8e-47ef-ac63-a4fb0ce98a41.png)
启动隧道时：
![image](https://user-images.githubusercontent.com/65562549/153771876-5fa0503f-2c04-4c23-ad94-5ec6b2144ea1.png)

**Comment by fakeboboliu** [comment]
嘛，虽然不提供支持，但是我去装了个这个 AidLearning 测试一下。

这个问题是 upx 与 proot 协作出现的问题，使用 `upx -d` 即可。 [frpc_linux_arm64.zip](https://github.com/natfrp/wiki/files/8058857/frpc_linux_arm64.zip)

此修复同样适用于使用 proot 运行其他发行版的 termux 用户。

顺便，[proot](https://github.com/proot-me/proot) 是在 GPLv2 条款下授权的，AidLearning （以及它的新名字 AidLux）很明显正在将 proot 作为他们整个系统构建的基础，很难讲这是否违反了相应的License。（当然，这只是我个人的一点评论，如果我对 GPLv2 的理解有错误，欢迎指出）。
